# Generated by Django 4.2.16 on 2025-10-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0002_alter_dsapracticechatdata_unique_together_and_more'),
        ('OpenAIService', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
        migrations.RemoveField(
            model_name='knowledgerepository',
            name='assistant_id',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='llm_config_name',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='llm_mode',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='streaming_enabled',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='tools',
        ),
        migrations.DeleteModel(
            name='ContentReference',
        ),
        migrations.DeleteModel(
            name='KnowledgeRepository',
        ),
        migrations.DeleteModel(
            name='OpenAIAssistant',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
